- gupb/model/coordinates.py
Subtraction of two coordinates adds values on x axis instead of subtracting them. 
This PR fixies this bug
> fix bad sign in sub_coords

- gupb/controller/botelka.py
- gupb/default_config.py
Authors: Karolina Piekarz, Piotr Kardaś
> BotElka - Version 1

- gupb/controller/botelka.py
- gupb/controller/ihavenoideawhatimdoing.py
Disclosure:
Bot korzysta z nazwy mapy przekazywanej w `arena_description.name` do załadowania pliku mapy z resources. Zakładam że skoro 
1. wiemy że gra będzie na mapie island bez broni debugowych (było to powiedziane na zajęciach)
2. metoda Arena.load jest statyczna to jest to trochę tak pomyślane
Jeżeli jednak nie, to jestem to w stanie prawdopodobnie wyłączyć i kierować się tylko wzrokiem bota
> IHaveNoIdeaWhatImDoingBot v1.0

- gupb/controller/claret_wolf.py
- gupb/default_config.py
- gupb/model/coordinates.py
Group: Paweł Zeller, Rafał Pych
> ClaretWolfBot#1

- gupb/controller/claret_wolf/claret_wolf.py
> ClaretWolf v5.0

- .gitignore
- gupb/controller/run4UrLife.py
- gupb/default_config.py
- gupb/view/render.py
- gupb/wsl2_config.py
Filip Komarzyniec, Artur Sokol
> Marwin Bot

- gupb/controller/ekonometron.py
Prototype created by Michał Kędra and Jan Proniewicz
> Ekonometron v3.0

- gupb/controller/killer/__init__.py
- gupb/controller/killer/killer.py
Autorzy: Michał Sobieraj, Michał Kmicikiewicz
Bot: Killer
> First approach to new player

- gupb/controller/shrek/__init__.py
- gupb/controller/shrek/shrek.py
- gupb/default_config.py
Team: Wiktoria Paluch, Weronika Owsianka
Controller has the abilities to: check if obstacle in front,  randomly make moves (higher prob on walk), attacks if his health is good
> Add Shrek Controller

- gupb/controller/dzikie_borsuki.py
Team: Sylwia Szlęk, Hanna Tabaszewska
> Dzikie_borsuki, round 1

- gupb/controller/spejson/__init__.py
- gupb/controller/spejson/spejson.py
Ekipa: Marcin Zięba, Maciej Wyleciał
Zawodnik: Spejson
> Spejson wjeżdża na dzielnię [v1]

- gupb/controller/AlephAlephZero/__init__.py
- gupb/controller/AlephAlephZero/aleph_aleph_zero.py
- gupb/controller/AlephAlephZero/attack_strategy.py
- gupb/controller/AlephAlephZero/guarding_strategy.py
- gupb/controller/AlephAlephZero/menhir_rush_strategy.py
- gupb/controller/AlephAlephZero/panic_strategy.py
- gupb/controller/AlephAlephZero/scanning_strategy.py
- gupb/controller/AlephAlephZero/scouting_strategy.py
- gupb/controller/AlephAlephZero/shortest_path.py
- gupb/controller/AlephAlephZero/strategy.py
- gupb/controller/AlephAlephZero/travel_strategy.py
- gupb/controller/AlephAlephZero/utils.py
- gupb/controller/AlephAlephZero/weapon_rush_strategy.py
Bot: AlephAlephZero
Skład: Weronika Lorenczyk, Wojciech Węgrzynek
> Um 2022 zima

- gupb/controller/tuptus/__init__.py
- gupb/controller/tuptus/tuptus.py
Bot: Tuptuś
Skład: Maciej Stroiński, Małgorzata Rucka
> Add Tuptuś player

- gupb/controller/random.py
- gupb/controller/sniezny_kockodan/__init__.py
- gupb/controller/sniezny_kockodan/kockodan.py
- gupb/controller/sniezny_kockodan/sniezny_kockodan.py
- profiling.md
Bot: Śniezny Kockodan
Grupa: Adam Kaczmarczyk, Paweł Karwowski
> Add Śniezny Kockodan

- gupb/controller/LordIcon/__init__.py
- gupb/controller/LordIcon/lordicon.py
Bot: Lord Icon
Grupa: Filip Twardy, Mikołaj Zatorski, Sebastian Kuśnierz
> Lord Icon [v1]

- gupb/controller/elvis/elvis.py
Konrad Bogusz
Elvis na Prochach
> add first iteration of bot

- gupb/controller/intercontinental_bajers/__init__.py
- gupb/controller/intercontinental_bajers/intercontinental_bajers.py
> add IntercontinentalBajers

- gupb/controller/shrek/shrek.py
Zespół: Wiktoria Paluch, Weronika Owsianka
Shrek version2
> Um 2022 zima ver2

- gupb/controller/dzikie_borsuki/dzikie_borsuki.py
now he can find a weapon, I guess
> dzikie_borsuki 21.10.2022 (3 week)

- gupb/controller/lord_icon/knowledge.py
- gupb/controller/lord_icon/lordicon.py
- gupb/controller/lord_icon/strategies/end_game_strategy.py
- gupb/controller/lord_icon/strategies/explore_strategy.py
- gupb/controller/lord_icon/strategies/kill_strategy.py
- gupb/controller/lord_icon/strategies/run_strategy.py
- gupb/controller/lord_icon/strategy.py
- gupb/controller/lord_icon/weapons/axe.py
- gupb/controller/lord_icon/weapons/bow_unloaded.py
Filip Twardy
Mikołaj Zatorski
Sebastian Kuśnierz
> Bandyta Marek

- gupb/controller/killer/killer.py
- gupb/controller/killer/structures.py
- gupb/controller/killer/utils.py
Major changes:
- Finding tree of shortest paths to every point on map via BFS (instead of DFS to one point)
- Changed point of interest (when nothing found on map) to randomly chosen point
- Simplified decide method
- Fixed bug with inversed coordinates
- Fixed bug with forgotten controller resetting
- Fixed bug with Killer seeing himself as an own victim
> Um 2022 zima, Killer_v4

- gupb/controller/elvis/elvis.py
Task 2 zrobiony, ale nie włączony, bo bot ma gorsze wyniki po włączeniu.
> elvis: and your k-arm bandits crashing [v4]

- requirements.txt
As above, Spejson needs some help from tensor flow but his original fork has too much changed that we ain't show yet
> Add tensorflow 2.7 to requirements

- gupb/controller/lord_icon/strategy.py
Do czasu _eBalu_ będzie dobrze uciekał od mgły
> [Lord Icon] Still fighting

- gupb/controller/dart/strategies.py
Add deep learning Dart. Provide a mechanism to make decisions based on attention from vision transformers. Right now, Dart is a fully autonomous bot.
> Deep learning Dart

- gupb/controller/AlphaGUPB/AlphaGUPB.py
> AlphaGUPB v0 round 1

- gupb/controller/pat_i_kot/__init__.py
> Pat i Kot i Świąteczne lenistwo

- gupb/controller/ancymon/ancymon.py
- gupb/controller/ancymon/environment.py
- gupb/controller/ancymon/strategies/hunter.py
- gupb/controller/ancymon/strategies/path_finder.py
> Ancymon v5

- gupb/controller/ancymon/strategies/hunter.py
- gupb/controller/ancymon/strategies/item_finder.py
> Ancymon V6

- gupb/controller/pat_i_kot/__init__.py
> Pat i Kot i noworoczne lenistwo
